services:
  n8n-puppeteer-runner:
    build:
      context: ./runner
      dockerfile: Dockerfile
    container_name: n8n-puppeteer-runner
    environment:
      - N8N_EXTERNAL_RUNNER_MODE=true
      - N8N_TASK_RUNNER_MODE=external
    restart: always
    networks:
      - n8n-network

networks:
  n8n-network:
    external: true
