version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-main
    environment:
      - N8N_TASK_RUNNER_MODE=external
      - N8N_TASK_RUNNER_URL=http://n8n-puppeteer-runner:5679
    ports:
      - "5678:5678"
    restart: always

  n8n-puppeteer-runner:
    build:
      context: ./runner
    container_name: n8n-puppeteer-runner
    environment:
      - N8N_EXTERNAL_RUNNER_MODE=true
      - N8N_TASK_RUNNER_MODE=external
    restart: always